# Generated by Django 5.2.6 on 2025-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default_user', 'Default_user'), ('notaire', 'Notaire'), ('geometre', 'Géomètre'), ('admin', 'Administrateur')], default='default_user', max_length=20),
        ),
    ]
