# Generated by Django 5.2.6 on 2025-10-16 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0007_alter_parcelle_certificat_hypotheque_and_more'),
        ('transactions', '0002_alter_transaction_etat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_active_transaction_per_parcelle',
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('etat__in', ['pending'])), fields=('parcelle',), name='unique_active_transaction_per_parcelle'),
        ),
    ]
