# Generated by Django 5.2.6 on 2025-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='role',
            field=models.CharField(choices=[('notaire', 'Notaire'), ('geometre', 'Géomètre'), ('acheteur', 'Acheteur'), ('vendeur', 'Vendeur')], max_length=20),
        ),
    ]
