# Generated by Django 5.2.6 on 2025-10-11 16:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_geometre_transaction_notaire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='vendeur',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendeur',
            field=models.ManyToManyField(blank=True, related_name='transactions_vendues', to=settings.AUTH_USER_MODEL),
        ),
    ]
