# Generated by Django 5.2.6 on 2025-10-11 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0007_alter_parcelle_certificat_hypotheque_and_more'),
        ('transactions', '0005_remove_transaction_vendeur_transaction_vendeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='vendeur',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vendeurs',
            field=models.ManyToManyField(related_name='transactions_vendues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='etat',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parcelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelles.parcelle'),
        ),
    ]
