# Generated by Django 5.2.6 on 2025-10-11 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_transaction_vendeur_transaction_vendeurs_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validation',
            unique_together={('transaction', 'role', 'user')},
        ),
    ]
