# Generated by Django 5.2.6 on 2025-09-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('taille_m2', models.FloatField()),
                ('prix_m2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('localisation', models.TextField()),
                ('statut', models.CharField(choices=[('available', 'Disponible'), ('sold', 'Vendu'), ('pending', 'En cours')], default='available', max_length=50)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('type_droit_propriete', models.CharField(blank=True, max_length=100, null=True)),
                ('usage', models.CharField(blank=True, max_length=100, null=True)),
                ('date_eng', models.DateField(auto_now_add=True)),
                ('plan_localisation', models.FileField(blank=True, null=True, upload_to='plans/')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('charge_parcelle', models.TextField(blank=True, null=True)),
                ('coordonnees', models.JSONField(help_text='Liste de coordonnées GeoJSON')),
            ],
        ),
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquisition', models.DateTimeField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcelles.parcelle')),
            ],
        ),
    ]
