# Generated by Django 5.2.6 on 2025-09-14 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='proprietaires',
            field=models.ManyToManyField(related_name='parcelles', through='parcelles.Possession', to=settings.AUTH_USER_MODEL),
        ),
    ]
