# Generated by Django 5.2.6 on 2025-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='coordonnees',
            field=models.TextField(help_text='Liste de coordonnées GeoJSON'),
        ),
    ]
