# Generated by Django 5.2.6 on 2025-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0003_alter_parcelle_coordonnees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possession',
            name='date_acquisition',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
