# Generated by Django 5.2.6 on 2025-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0004_alter_possession_date_acquisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='certificat_hypotheque',
            field=models.FileField(default=None, upload_to='hypotheque/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='plan_cadastral',
            field=models.FileField(default=None, upload_to='plancadastral/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcelle',
            name='titre_foncier',
            field=models.FileField(default=None, upload_to='titrefoncier/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='plan_localisation',
            field=models.FileField(default=None, upload_to='plans/'),
            preserve_default=False,
        ),
    ]
