# Generated by Django 5.2.6 on 2025-09-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0005_parcelle_certificat_hypotheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='certificat_hypotheque',
            field=models.FileField(blank=True, null=True, upload_to='hypotheque/'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='plan_cadastral',
            field=models.FileField(blank=True, null=True, upload_to='plancadastral/'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='plan_localisation',
            field=models.FileField(blank=True, null=True, upload_to='plans/'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='titre_foncier',
            field=models.FileField(blank=True, null=True, upload_to='titrefoncier/'),
        ),
    ]
