# Generated by Django 5.2.6 on 2025-09-14 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0002_planlocalisation'),
        ('parcelles', '0006_alter_parcelle_certificat_hypotheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='certificat_hypotheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.certificathypotheque'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='plan_cadastral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.plancadastral'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='plan_localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.planlocalisation'),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='titre_foncier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Documents.titrefoncier'),
        ),
    ]
